import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import CTA from "@/components/CTA";

const poppins = Poppins({weight:["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"], subsets: ["latin","latin-ext"]});

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Header />
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
                <CTA />
                {children}
            </main>
      </body>
    </html>
  );
}
